### PR TITLE
Use glide for dependency management

### PR DESCRIPTION
**Pull request by hanzei**
### What does this PR do?
- Move to glide for dependency management
- Update dependencies
- Not longer run tests of vendor packages

## Why is this PR needed?
Since [Godep](https://github.com/tools/godep) is not longer properly maintained (last commit was about a year ago) I propose to move to [glide](https://github.com/Masterminds/glide). It is a well maintained project and wide used.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
I wonder if it would make sense to use https://github.com/golang/dep given that it is on track to become the official dependency tool

**Comment by philtay** [comment]
`dep` is the way to go (pun intended...). I was about to open a PR for that but I noticed that we depend on https://github.com/stretchr/objx too. Of course it's not maintained. @dignifiedquire please fork it under this org and tag the last commit as 1.0.0. In this way all of our dependencies will use semver (I've already checked the other two). I'll then open a PR to use `dep`.

**Comment by dignifiedquire** [comment]
Fork is done https://github.com/test-go/objx, if you could make a pr to rename things, I'll tag it as v1.0.0

**Comment by philtay** [comment]
@dignifiedquire done

**Comment by hanzei** [comment]
Closing this PR in favour of #6

**Pull request closed without merging**
