### PR TITLE
Adopt to standard license file

### LINKED ISSUE #10: adopt standard license file
Adopt a standard and GitHub-detectable license file.

https://help.github.com/articles/licensing-a-repository/#detecting-a-license

The current license type (MIT) will be retained.

### PR DESCRIPTION
**Pull request by hanzei**
Fixes #10

### CODE REVIEW

**Comment by philtay** [comment]
We should not change the original copyright line. Just add a new one below:

```
Copyright (c) 2012 - 2013 Mat Ryer and Tyler Bunnell
Copyright (c) 2017 testify contributors
```

**Comment by hanzei** [comment]
Changes made

**Comment by philtay** [comment]
Unfortunately we can't write ```Copyright (c) 2017-present```. Copyright doesn't work like that :-( ```Copyright (c) 2017``` is ok now. ```Copyright (c) 2017 - 2018``` will be ok starting from Jan 1st. The license must be updated every year.

**Comment by hanzei** [comment]
@philtay Does this look better?

**Review by philtay — APPROVED** [review]

**Pull request merged**
